[package]
name = "nx"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2018"

[dependencies]
linked_list_allocator = "0.9"
paste = "1.0"
logpacket = { git = "https://github.com/aarch64-switch-rs/logpacket" }

[dependencies.derivative]
version = "2.1.1"
default-features = false
features = ["use_core"]

[dependencies.arrayvec]
version = "0.5.1"
default-features = false
features = []
